export const SERVICE_TYPES = [
  { value: "boroscopia", label: "Boroscopia" },
  { value: "pre_purchase", label: "Pré-Purchase" },
  { value: "annual_inspection", label: "Inspeção Anual" },
  { value: "progressive", label: "Inspeção Progressiva" },
  { value: "cva", label: "CVA" },
  { value: "50h", label: "Revisão 50h" },
  { value: "100h", label: "Revisão 100h" },
  { value: "200h", label: "Revisão 200h" },
  { value: "300h", label: "Revisão 300h" },
  { value: "400h", label: "Revisão 400h" },
  { value: "500h", label: "Revisão 500h" },
  { value: "600h", label: "Revisão 600h" },
  { value: "1000h", label: "Revisão 1000h" },
  { value: "ad_compliance", label: "AD Compliance" },
  { value: "sb_compliance", label: "SB Compliance" },
  { value: "altimetry_transponder", label: "Altimetria/Transponder" },
  { value: "compass_calibration", label: "Calibração da Bússola" },
  { value: "weighing_balance", label: "Pesagem e Balanceamento" },
  { value: "technical_wash", label: "Lavagem Técnica" },
  { value: "off_base", label: "Serviço Fora de Base" },
  { value: "appendix_d", label: "Apêndice D" },
  { value: "discrepancies", label: "Discrepâncias" },
  { value: "iam", label: "IAM - Inspeção Anual de Manutenção" },
  { value: "engine_overhaul", label: "Overhaul de Motor" },
  { value: "propeller_overhaul", label: "Overhaul de Hélice" },
  { value: "engine_tbo", label: "TBO Motor" },
  { value: "propeller_tbo", label: "TBO Hélice" },
  { value: "magneto_inspection", label: "Inspeção de Magneto" },
  { value: "spark_plug", label: "Troca de Velas" },
  { value: "oil_change", label: "Troca de Óleo" },
  { value: "filter_change", label: "Troca de Filtros" },
  { value: "fuel_hose", label: "Troca de Mangueira de Combustível" },
  { value: "oil_hose", label: "Troca de Mangueira de Óleo" },
  { value: "battery_service", label: "Serviço de Bateria" },
  { value: "tire_replacement", label: "Troca de Pneus" },
  { value: "brake_service", label: "Serviço de Freios" },
  { value: "landing_gear", label: "Inspeção Trem de Pouso" },
  { value: "fire_extinguisher", label: "Inspeção Extintor" },
  { value: "elt_inspection", label: "Inspeção ELT" },
  { value: "oxygen_system", label: "Sistema de Oxigênio" },
  { value: "pitot_static", label: "Sistema Pitot-Estático" },
  { value: "avionics", label: "Manutenção Aviônicos" },
  { value: "autopilot", label: "Manutenção Piloto Automático" },
  { value: "gps_update", label: "Atualização GPS/Database" },
  { value: "interior", label: "Manutenção Interior" },
  { value: "paint", label: "Pintura" },
  { value: "structural_repair", label: "Reparo Estrutural" },
  { value: "corrosion_inspection", label: "Inspeção de Corrosão" },
  { value: "ndt", label: "Ensaio Não Destrutivo (END)" },
  { value: "rigging", label: "Regulagem de Comandos" },
  { value: "engine_run", label: "Teste de Motor (Run-up)" },
  { value: "test_flight", label: "Voo de Teste" },
  { value: "ferry_flight", label: "Voo de Traslado" },
  { value: "recovery", label: "Recuperação/Resgate" },
  { value: "warranty", label: "Serviço em Garantia" },
  { value: "modification", label: "Modificação/STC" },
  { value: "import_export", label: "Importação/Exportação" },
  { value: "post_harvest", label: "Pós-Safra" },
  { value: "pre_harvest", label: "Pré-Safra" },
  { value: "ag_hopper_inspection", label: "Inspeção Hopper (Agrícola)" },
  { value: "ag_spray_system", label: "Sistema de Pulverização" },
  { value: "ag_spray_calibration", label: "Calibração de Barra de Pulverização" },
  { value: "ag_nozzle_replacement", label: "Troca de Bicos de Pulverização" },
  { value: "ag_pump_service", label: "Manutenção Bomba Agrícola" },
  { value: "ag_micronair", label: "Manutenção Micronair/Atomizador" },
  { value: "ag_dispersal_system", label: "Sistema Dispersor de Sólidos"  },
  { value: "ag_gps_dgps", label: "GPS/DGPS Agrícola" },
  { value: "ag_flow_control", label: "Controle de Vazão (Flow Control)" },
  { value: "ag_chemical_wash", label: "Lavagem Descontaminação Química" },
  { value: "ag_corrosion_treatment", label: "Tratamento Anticorrosivo Agrícola" },
  { value: "ag_cable_cutter", label: "Inspeção Cortador de Cabos" },
  { value: "ag_mirror_inspection", label: "Inspeção Espelhos Agrícola" },
  { value: "ag_seasonal_overhaul", label: "Revisão Sazonal Agrícola" },
  { value: "other", label: "Outro" },
] as const;

export const MAINTENANCE_ITEMS = [
  { value: "cva", label: "CVA" },
  { value: "iam", label: "IAM" },
  { value: "revision_50h", label: "Revisão 50h" },
  { value: "revision_100h", label: "Revisão 100h" },
  { value: "revision_200h", label: "Revisão 200h" },
  { value: "revision_400h", label: "Revisão 400h" },
  { value: "revision_500h", label: "Revisão 500h" },
  { value: "revision_600h", label: "Revisão 600h" },
  { value: "revision_1000h", label: "Revisão 1000h" },
  { value: "altimetry_transponder", label: "Altimetria/Transponder" },
  { value: "compass_calibration", label: "Calibração Bússola" },
  { value: "weighing_balance", label: "Pesagem" },
  { value: "engine_tbo", label: "TBO Motor" },
  { value: "propeller_tbo", label: "TBO Hélice" },
  { value: "ad_compliance", label: "AD" },
  { value: "magneto", label: "Magneto" },
  { value: "fuel_hose", label: "Mangueira Combustível" },
  { value: "oil_hose", label: "Mangueira Óleo" },
  { value: "battery", label: "Bateria" },
  { value: "fire_ext", label: "Extintor" },
] as const;

export const DOC_TYPES = [
  { value: "AMM", label: "AMM" },
  { value: "POH", label: "POH" },
  { value: "IPC", label: "IPC" },
  { value: "SOP", label: "SOP" },
  { value: "SB", label: "Service Bulletin" },
  { value: "AD", label: "Airworthiness Directive" },
  { value: "OTHER", label: "Outro" },
] as const;

export const AIRCRAFT_STATUS = [
  { value: "active", label: "Ativa" },
  { value: "maintenance", label: "Em Manutenção" },
  { value: "inactive", label: "Inativa" },
  { value: "non_conform", label: "Não Conforme" },
] as const;

export const AIRCRAFT_CATEGORIES = [
  { value: "agricultural", label: "Agrícola" },
  { value: "executive", label: "Executiva" },
  { value: "instruction", label: "Instrução" },
  { value: "air_taxi", label: "Táxi Aéreo" },
  { value: "cargo", label: "Carga" },
  { value: "private", label: "Particular" },
  { value: "experimental", label: "Experimental" },
  { value: "helicopter", label: "Helicóptero" },
  { value: "other", label: "Outra" },
] as const;

export const SERVICE_STATUS = [
  { value: "pending", label: "Pendente" },
  { value: "in_progress", label: "Em Andamento" },
  { value: "completed", label: "Concluído" },
  { value: "cancelled", label: "Cancelado" },
] as const;

export const PART_STATUS = [
  { value: "stock", label: "Em Estoque" },
  { value: "installed", label: "Instalada" },
  { value: "scrapped", label: "Descartada" },
  { value: "sent_repair", label: "Enviada p/ Reparo" },
] as const;

export const PART_CONDITION = [
  { value: "new", label: "Nova" },
  { value: "serviceable", label: "Serviceable" },
  { value: "unserviceable", label: "Unserviceable" },
   { value: "overhauled", label: "Overhauled" },
   { value: "repairable", label: "Reparável" },
   { value: "damaged", label: "Estragada / Danificada" },
   { value: "consumable", label: "Insumo / Consumível" },
   { value: "workshop_use", label: "Uso de Oficina" },
   { value: "quarantine", label: "Em Quarentena" },
   { value: "expired", label: "Vencida" },
   { value: "loaner", label: "Empréstimo" },
   { value: "core", label: "Core / Devolução" },
 ] as const;
 
 export const SHIPMENT_STATUS = [
   { value: "sent", label: "Enviado" },
   { value: "in_repair", label: "Em Reparo" },
   { value: "received", label: "Recebido" },
   { value: "cancelled", label: "Cancelado" },
 ] as const;

export const SECURITY_QUESTIONS = [
  "Qual o nome do seu primeiro animal de estimação?",
  "Em que cidade você nasceu?",
  "Qual o nome de solteira da sua mãe?",
  "Qual a marca do seu primeiro carro?",
  "Qual o nome da sua escola primária?",
  "Qual seu prato favorito?",
] as const;

export const FLIGHT_NATURE = [
  { value: "private", label: "Privado (TPX)" },
  { value: "commercial", label: "Comercial (TPC)" },
  { value: "instruction", label: "Instrução (PRI)" },
  { value: "maintenance", label: "Voo de Experiência" },
  { value: "ferry", label: "Traslado" },
] as const;
