/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RabRouteImport } from './routes/rab'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AircraftRouteImport } from './routes/aircraft'
import { Route as IndexRouteImport } from './routes/index'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RabRoute = RabRouteImport.update({
  id: '/rab',
  path: '/rab',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AircraftRoute = AircraftRouteImport.update({
  id: '/aircraft',
  path: '/aircraft',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aircraft': typeof AircraftRoute
  '/auth': typeof AuthRoute
  '/backup': typeof BackupRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/parts': typeof PartsRoute
  '/rab': typeof RabRoute
  '/services': typeof ServicesRoute
  '/shipments': typeof ShipmentsRoute
  '/usage': typeof UsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aircraft': typeof AircraftRoute
  '/auth': typeof AuthRoute
  '/backup': typeof BackupRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/parts': typeof PartsRoute
  '/rab': typeof RabRoute
  '/services': typeof ServicesRoute
  '/shipments': typeof ShipmentsRoute
  '/usage': typeof UsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aircraft': typeof AircraftRoute
  '/auth': typeof AuthRoute
  '/backup': typeof BackupRoute
  '/dashboard': typeof DashboardRoute
  '/library': typeof LibraryRoute
  '/parts': typeof PartsRoute
  '/rab': typeof RabRoute
  '/services': typeof ServicesRoute
  '/shipments': typeof ShipmentsRoute
  '/usage': typeof UsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aircraft'
    | '/auth'
    | '/backup'
    | '/dashboard'
    | '/library'
    | '/parts'
    | '/rab'
    | '/services'
    | '/shipments'
    | '/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aircraft'
    | '/auth'
    | '/backup'
    | '/dashboard'
    | '/library'
    | '/parts'
    | '/rab'
    | '/services'
    | '/shipments'
    | '/usage'
  id:
    | '__root__'
    | '/'
    | '/aircraft'
    | '/auth'
    | '/backup'
    | '/dashboard'
    | '/library'
    | '/parts'
    | '/rab'
    | '/services'
    | '/shipments'
    | '/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AircraftRoute: typeof AircraftRoute
  AuthRoute: typeof AuthRoute
  BackupRoute: typeof BackupRoute
  DashboardRoute: typeof DashboardRoute
  LibraryRoute: typeof LibraryRoute
  PartsRoute: typeof PartsRoute
  RabRoute: typeof RabRoute
  ServicesRoute: typeof ServicesRoute
  ShipmentsRoute: typeof ShipmentsRoute
  UsageRoute: typeof UsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rab': {
      id: '/rab'
      path: '/rab'
      fullPath: '/rab'
      preLoaderRoute: typeof RabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aircraft': {
      id: '/aircraft'
      path: '/aircraft'
      fullPath: '/aircraft'
      preLoaderRoute: typeof AircraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AircraftRoute: AircraftRoute,
  AuthRoute: AuthRoute,
  BackupRoute: BackupRoute,
  DashboardRoute: DashboardRoute,
  LibraryRoute: LibraryRoute,
  PartsRoute: PartsRoute,
  RabRoute: RabRoute,
  ServicesRoute: ServicesRoute,
  ShipmentsRoute: ShipmentsRoute,
  UsageRoute: UsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
