/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShipmentsRouteImport } from './routes/shipments'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServicePricesRouteImport } from './routes/service-prices'
import { Route as RabRouteImport } from './routes/rab'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FlightLogsRouteImport } from './routes/flight-logs'
import { Route as DemandsRouteImport } from './routes/demands'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplicabilityRouteImport } from './routes/applicability'
import { Route as AircraftRouteImport } from './routes/aircraft'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsRoute = ShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicePricesRoute = ServicePricesRouteImport.update({
  id: '/service-prices',
  path: '/service-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const RabRoute = RabRouteImport.update({
  id: '/rab',
  path: '/rab',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightLogsRoute = FlightLogsRouteImport.update({
  id: '/flight-logs',
  path: '/flight-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemandsRoute = DemandsRouteImport.update({
  id: '/demands',
  path: '/demands',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicabilityRoute = ApplicabilityRouteImport.update({
  id: '/applicability',
  path: '/applicability',
  getParentRoute: () => rootRouteImport,
} as any)
const AircraftRoute = AircraftRouteImport.update({
  id: '/aircraft',
  path: '/aircraft',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aircraft': typeof AircraftRoute
  '/applicability': typeof ApplicabilityRoute
  '/auth': typeof AuthRoute
  '/backup': typeof BackupRoute
  '/dashboard': typeof DashboardRoute
  '/demands': typeof DemandsRoute
  '/flight-logs': typeof FlightLogsRoute
  '/library': typeof LibraryRoute
  '/parts': typeof PartsRoute
  '/pending': typeof PendingRoute
  '/rab': typeof RabRoute
  '/service-prices': typeof ServicePricesRoute
  '/services': typeof ServicesRoute
  '/shipments': typeof ShipmentsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suppliers': typeof SuppliersRoute
  '/timeline': typeof TimelineRoute
  '/usage': typeof UsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aircraft': typeof AircraftRoute
  '/applicability': typeof ApplicabilityRoute
  '/auth': typeof AuthRoute
  '/backup': typeof BackupRoute
  '/dashboard': typeof DashboardRoute
  '/demands': typeof DemandsRoute
  '/flight-logs': typeof FlightLogsRoute
  '/library': typeof LibraryRoute
  '/parts': typeof PartsRoute
  '/pending': typeof PendingRoute
  '/rab': typeof RabRoute
  '/service-prices': typeof ServicePricesRoute
  '/services': typeof ServicesRoute
  '/shipments': typeof ShipmentsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suppliers': typeof SuppliersRoute
  '/timeline': typeof TimelineRoute
  '/usage': typeof UsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/aircraft': typeof AircraftRoute
  '/applicability': typeof ApplicabilityRoute
  '/auth': typeof AuthRoute
  '/backup': typeof BackupRoute
  '/dashboard': typeof DashboardRoute
  '/demands': typeof DemandsRoute
  '/flight-logs': typeof FlightLogsRoute
  '/library': typeof LibraryRoute
  '/parts': typeof PartsRoute
  '/pending': typeof PendingRoute
  '/rab': typeof RabRoute
  '/service-prices': typeof ServicePricesRoute
  '/services': typeof ServicesRoute
  '/shipments': typeof ShipmentsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/suppliers': typeof SuppliersRoute
  '/timeline': typeof TimelineRoute
  '/usage': typeof UsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aircraft'
    | '/applicability'
    | '/auth'
    | '/backup'
    | '/dashboard'
    | '/demands'
    | '/flight-logs'
    | '/library'
    | '/parts'
    | '/pending'
    | '/rab'
    | '/service-prices'
    | '/services'
    | '/shipments'
    | '/sitemap.xml'
    | '/suppliers'
    | '/timeline'
    | '/usage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/aircraft'
    | '/applicability'
    | '/auth'
    | '/backup'
    | '/dashboard'
    | '/demands'
    | '/flight-logs'
    | '/library'
    | '/parts'
    | '/pending'
    | '/rab'
    | '/service-prices'
    | '/services'
    | '/shipments'
    | '/sitemap.xml'
    | '/suppliers'
    | '/timeline'
    | '/usage'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/aircraft'
    | '/applicability'
    | '/auth'
    | '/backup'
    | '/dashboard'
    | '/demands'
    | '/flight-logs'
    | '/library'
    | '/parts'
    | '/pending'
    | '/rab'
    | '/service-prices'
    | '/services'
    | '/shipments'
    | '/sitemap.xml'
    | '/suppliers'
    | '/timeline'
    | '/usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AircraftRoute: typeof AircraftRoute
  ApplicabilityRoute: typeof ApplicabilityRoute
  AuthRoute: typeof AuthRoute
  BackupRoute: typeof BackupRoute
  DashboardRoute: typeof DashboardRoute
  DemandsRoute: typeof DemandsRoute
  FlightLogsRoute: typeof FlightLogsRoute
  LibraryRoute: typeof LibraryRoute
  PartsRoute: typeof PartsRoute
  PendingRoute: typeof PendingRoute
  RabRoute: typeof RabRoute
  ServicePricesRoute: typeof ServicePricesRoute
  ServicesRoute: typeof ServicesRoute
  ShipmentsRoute: typeof ShipmentsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuppliersRoute: typeof SuppliersRoute
  TimelineRoute: typeof TimelineRoute
  UsageRoute: typeof UsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments': {
      id: '/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof ShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-prices': {
      id: '/service-prices'
      path: '/service-prices'
      fullPath: '/service-prices'
      preLoaderRoute: typeof ServicePricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rab': {
      id: '/rab'
      path: '/rab'
      fullPath: '/rab'
      preLoaderRoute: typeof RabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight-logs': {
      id: '/flight-logs'
      path: '/flight-logs'
      fullPath: '/flight-logs'
      preLoaderRoute: typeof FlightLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demands': {
      id: '/demands'
      path: '/demands'
      fullPath: '/demands'
      preLoaderRoute: typeof DemandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applicability': {
      id: '/applicability'
      path: '/applicability'
      fullPath: '/applicability'
      preLoaderRoute: typeof ApplicabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aircraft': {
      id: '/aircraft'
      path: '/aircraft'
      fullPath: '/aircraft'
      preLoaderRoute: typeof AircraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AircraftRoute: AircraftRoute,
  ApplicabilityRoute: ApplicabilityRoute,
  AuthRoute: AuthRoute,
  BackupRoute: BackupRoute,
  DashboardRoute: DashboardRoute,
  DemandsRoute: DemandsRoute,
  FlightLogsRoute: FlightLogsRoute,
  LibraryRoute: LibraryRoute,
  PartsRoute: PartsRoute,
  PendingRoute: PendingRoute,
  RabRoute: RabRoute,
  ServicePricesRoute: ServicePricesRoute,
  ServicesRoute: ServicesRoute,
  ShipmentsRoute: ShipmentsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuppliersRoute: SuppliersRoute,
  TimelineRoute: TimelineRoute,
  UsageRoute: UsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
